"""
Hand-authored seed specs for the phone models most commonly seen across the
scraped store catalogs (data/*_products.csv). This is NOT scraped from any
third-party spec database — it's general public-knowledge facts (display
size, chipset, camera MP, battery capacity, etc.) written out by hand as a
starting dataset for the compare feature.

Coverage is intentionally limited to popular models. Values are best-effort
and approximate for lesser-known regional variants — treat this as a seed,
not an authoritative source. `model_key` must be a normalized (lowercase,
alnum + spaces only) substring that uniquely identifies the model within its
brand; matching picks the longest `model_key` that appears in the product's
normalized name, so more specific variants (e.g. "pro max") must be listed
before their shorter prefixes (e.g. "pro") — order in this list doesn't
matter since the matcher sorts by length itself, but keep this in mind if
you add ambiguous keys.
"""

SPEC_SEED: list[dict] = [
    # ── Apple ────────────────────────────────────────────────────────────────
    {
        "brand": "apple", "model_key": "iphone 13", "display_name": "Apple iPhone 13",
        "display": "6.1\" OLED, 60Hz, 1170x2532", "chipset": "Apple A15 Bionic",
        "ram_options": ["4GB"], "storage_options": ["128GB", "256GB", "512GB"],
        "main_camera": "12MP + 12MP (dual, wide + ultrawide)", "selfie_camera": "12MP",
        "battery_mah": 3240, "charging": "20W wired, 15W MagSafe", "os": "iOS 15 (upgradable)",
        "body": "Aluminum frame, glass back, IP68", "release_year": 2021,
    },
    {
        "brand": "apple", "model_key": "iphone 14", "display_name": "Apple iPhone 14",
        "display": "6.1\" OLED, 60Hz, 1170x2532", "chipset": "Apple A15 Bionic (5-core GPU)",
        "ram_options": ["6GB"], "storage_options": ["128GB", "256GB", "512GB"],
        "main_camera": "12MP + 12MP (dual, wide + ultrawide)", "selfie_camera": "12MP",
        "battery_mah": 3279, "charging": "20W wired, 15W MagSafe", "os": "iOS 16 (upgradable)",
        "body": "Aluminum frame, glass back, IP68", "release_year": 2022,
    },
    {
        "brand": "apple", "model_key": "iphone 15", "display_name": "Apple iPhone 15",
        "display": "6.1\" OLED, 60Hz, 1179x2556", "chipset": "Apple A16 Bionic",
        "ram_options": ["6GB"], "storage_options": ["128GB", "256GB", "512GB"],
        "main_camera": "48MP + 12MP (dual, wide + ultrawide)", "selfie_camera": "12MP",
        "battery_mah": 3349, "charging": "20W wired, 15W MagSafe, USB-C", "os": "iOS 17 (upgradable)",
        "body": "Aluminum frame, glass back, IP68", "release_year": 2023,
    },
    {
        "brand": "apple", "model_key": "iphone 16 plus", "display_name": "Apple iPhone 16 Plus",
        "display": "6.7\" OLED, 60Hz, 1290x2796", "chipset": "Apple A18",
        "ram_options": ["8GB"], "storage_options": ["128GB", "256GB", "512GB"],
        "main_camera": "48MP + 12MP (dual, wide + ultrawide)", "selfie_camera": "12MP",
        "battery_mah": 4674, "charging": "25W wired, 25W MagSafe, USB-C", "os": "iOS 18 (upgradable)",
        "body": "Aluminum frame, glass back, IP68", "release_year": 2024,
    },
    {
        "brand": "apple", "model_key": "iphone 16", "display_name": "Apple iPhone 16",
        "display": "6.1\" OLED, 60Hz, 1179x2556", "chipset": "Apple A18",
        "ram_options": ["8GB"], "storage_options": ["128GB", "256GB", "512GB"],
        "main_camera": "48MP + 12MP (dual, wide + ultrawide)", "selfie_camera": "12MP",
        "battery_mah": 3561, "charging": "25W wired, 25W MagSafe, USB-C", "os": "iOS 18 (upgradable)",
        "body": "Aluminum frame, glass back, IP68", "release_year": 2024,
    },
    {
        "brand": "apple", "model_key": "iphone 17 pro max", "display_name": "Apple iPhone 17 Pro Max",
        "display": "6.9\" LTPO OLED, 120Hz, 1320x2868", "chipset": "Apple A19 Pro",
        "ram_options": ["12GB"], "storage_options": ["256GB", "512GB", "1TB", "2TB"],
        "main_camera": "48MP + 48MP + 48MP (triple, 4x tele)", "selfie_camera": "18MP",
        "battery_mah": 5000, "charging": "40W wired, 25W MagSafe, USB-C", "os": "iOS 26",
        "body": "Titanium frame, IP68", "release_year": 2025,
    },
    {
        "brand": "apple", "model_key": "iphone 17 pro", "display_name": "Apple iPhone 17 Pro",
        "display": "6.3\" LTPO OLED, 120Hz, 1206x2622", "chipset": "Apple A19 Pro",
        "ram_options": ["12GB"], "storage_options": ["256GB", "512GB", "1TB"],
        "main_camera": "48MP + 48MP + 48MP (triple, 4x tele)", "selfie_camera": "18MP",
        "battery_mah": 4200, "charging": "40W wired, 25W MagSafe, USB-C", "os": "iOS 26",
        "body": "Titanium frame, IP68", "release_year": 2025,
    },
    {
        "brand": "apple", "model_key": "iphone 17", "display_name": "Apple iPhone 17",
        "display": "6.3\" OLED, 120Hz, 1206x2622", "chipset": "Apple A19",
        "ram_options": ["8GB"], "storage_options": ["256GB", "512GB"],
        "main_camera": "48MP + 48MP (dual, wide + ultrawide)", "selfie_camera": "18MP",
        "battery_mah": 3692, "charging": "30W wired, 25W MagSafe, USB-C", "os": "iOS 26",
        "body": "Aluminum frame, glass back, IP68", "release_year": 2025,
    },

    {
        "brand": "apple", "model_key": "iphone xr", "display_name": "Apple iPhone XR",
        "display": "6.1\" LCD, 60Hz, 828x1792", "chipset": "Apple A12 Bionic",
        "ram_options": ["3GB"], "storage_options": ["64GB", "128GB", "256GB"],
        "main_camera": "12MP (single)", "selfie_camera": "7MP",
        "battery_mah": 2942, "charging": "18W wired", "os": "iOS 12 (upgradable)",
        "body": "Aluminum frame, glass back, IP67", "release_year": 2018,
    },
    {
        "brand": "apple", "model_key": "iphone 11 pro max", "display_name": "Apple iPhone 11 Pro Max",
        "display": "6.5\" OLED, 60Hz, 1242x2688", "chipset": "Apple A13 Bionic",
        "ram_options": ["4GB"], "storage_options": ["64GB", "256GB", "512GB"],
        "main_camera": "12MP + 12MP + 12MP (triple)", "selfie_camera": "12MP",
        "battery_mah": 3969, "charging": "18W wired, 7.5W wireless", "os": "iOS 13 (upgradable)",
        "body": "Stainless steel frame, glass back, IP68", "release_year": 2019,
    },
    {
        "brand": "apple", "model_key": "iphone 11 pro", "display_name": "Apple iPhone 11 Pro",
        "display": "5.8\" OLED, 60Hz, 1125x2436", "chipset": "Apple A13 Bionic",
        "ram_options": ["4GB"], "storage_options": ["64GB", "256GB", "512GB"],
        "main_camera": "12MP + 12MP + 12MP (triple)", "selfie_camera": "12MP",
        "battery_mah": 3046, "charging": "18W wired, 7.5W wireless", "os": "iOS 13 (upgradable)",
        "body": "Stainless steel frame, glass back, IP68", "release_year": 2019,
    },
    {
        "brand": "apple", "model_key": "iphone 11", "display_name": "Apple iPhone 11",
        "display": "6.1\" LCD, 60Hz, 828x1792", "chipset": "Apple A13 Bionic",
        "ram_options": ["4GB"], "storage_options": ["64GB", "128GB", "256GB"],
        "main_camera": "12MP + 12MP (dual)", "selfie_camera": "12MP",
        "battery_mah": 3110, "charging": "18W wired, 7.5W wireless", "os": "iOS 13 (upgradable)",
        "body": "Aluminum frame, glass back, IP68", "release_year": 2019,
    },
    {
        "brand": "apple", "model_key": "iphone 12 pro max", "display_name": "Apple iPhone 12 Pro Max",
        "display": "6.7\" OLED, 60Hz, 1284x2778", "chipset": "Apple A14 Bionic",
        "ram_options": ["6GB"], "storage_options": ["128GB", "256GB", "512GB"],
        "main_camera": "12MP + 12MP + 12MP (triple, LiDAR)", "selfie_camera": "12MP",
        "battery_mah": 3687, "charging": "20W wired, 15W MagSafe", "os": "iOS 14 (upgradable)",
        "body": "Stainless steel frame, glass back, IP68", "release_year": 2020,
    },
    {
        "brand": "apple", "model_key": "iphone 12 pro", "display_name": "Apple iPhone 12 Pro",
        "display": "6.1\" OLED, 60Hz, 1170x2532", "chipset": "Apple A14 Bionic",
        "ram_options": ["6GB"], "storage_options": ["128GB", "256GB", "512GB"],
        "main_camera": "12MP + 12MP + 12MP (triple, LiDAR)", "selfie_camera": "12MP",
        "battery_mah": 2815, "charging": "20W wired, 15W MagSafe", "os": "iOS 14 (upgradable)",
        "body": "Stainless steel frame, glass back, IP68", "release_year": 2020,
    },
    {
        "brand": "apple", "model_key": "iphone 12 mini", "display_name": "Apple iPhone 12 mini",
        "display": "5.4\" OLED, 60Hz, 1080x2340", "chipset": "Apple A14 Bionic",
        "ram_options": ["4GB"], "storage_options": ["64GB", "128GB", "256GB"],
        "main_camera": "12MP + 12MP (dual)", "selfie_camera": "12MP",
        "battery_mah": 2227, "charging": "20W wired, 12W MagSafe", "os": "iOS 14 (upgradable)",
        "body": "Aluminum frame, glass back, IP68", "release_year": 2020,
    },
    {
        "brand": "apple", "model_key": "iphone 12", "display_name": "Apple iPhone 12",
        "display": "6.1\" OLED, 60Hz, 1170x2532", "chipset": "Apple A14 Bionic",
        "ram_options": ["4GB"], "storage_options": ["64GB", "128GB", "256GB"],
        "main_camera": "12MP + 12MP (dual)", "selfie_camera": "12MP",
        "battery_mah": 2815, "charging": "20W wired, 15W MagSafe", "os": "iOS 14 (upgradable)",
        "body": "Aluminum frame, glass back, IP68", "release_year": 2020,
    },
    {
        "brand": "apple", "model_key": "iphone 13 pro max", "display_name": "Apple iPhone 13 Pro Max",
        "display": "6.7\" LTPO OLED, 120Hz, 1284x2778", "chipset": "Apple A15 Bionic",
        "ram_options": ["6GB"], "storage_options": ["128GB", "256GB", "512GB", "1TB"],
        "main_camera": "12MP + 12MP + 12MP (triple, 3x tele)", "selfie_camera": "12MP",
        "battery_mah": 4352, "charging": "20W wired, 15W MagSafe", "os": "iOS 15 (upgradable)",
        "body": "Stainless steel frame, glass back, IP68", "release_year": 2021,
    },
    {
        "brand": "apple", "model_key": "iphone 13 pro", "display_name": "Apple iPhone 13 Pro",
        "display": "6.1\" LTPO OLED, 120Hz, 1170x2532", "chipset": "Apple A15 Bionic",
        "ram_options": ["6GB"], "storage_options": ["128GB", "256GB", "512GB", "1TB"],
        "main_camera": "12MP + 12MP + 12MP (triple, 3x tele)", "selfie_camera": "12MP",
        "battery_mah": 3095, "charging": "20W wired, 15W MagSafe", "os": "iOS 15 (upgradable)",
        "body": "Stainless steel frame, glass back, IP68", "release_year": 2021,
    },
    {
        "brand": "apple", "model_key": "iphone 13 mini", "display_name": "Apple iPhone 13 mini",
        "display": "5.4\" OLED, 60Hz, 1080x2340", "chipset": "Apple A15 Bionic",
        "ram_options": ["4GB"], "storage_options": ["128GB", "256GB", "512GB"],
        "main_camera": "12MP + 12MP (dual)", "selfie_camera": "12MP",
        "battery_mah": 2406, "charging": "20W wired, 15W MagSafe", "os": "iOS 15 (upgradable)",
        "body": "Aluminum frame, glass back, IP68", "release_year": 2021,
    },
    {
        "brand": "apple", "model_key": "iphone 15 pro max", "display_name": "Apple iPhone 15 Pro Max",
        "display": "6.7\" LTPO OLED, 120Hz, 1290x2796", "chipset": "Apple A17 Pro",
        "ram_options": ["8GB"], "storage_options": ["256GB", "512GB", "1TB"],
        "main_camera": "48MP + 12MP + 12MP (triple, 5x periscope tele)", "selfie_camera": "12MP",
        "battery_mah": 4441, "charging": "27W wired, 15W MagSafe, USB-C", "os": "iOS 17 (upgradable)",
        "body": "Titanium frame, IP68", "release_year": 2023,
    },
    {
        "brand": "apple", "model_key": "iphone 15 pro", "display_name": "Apple iPhone 15 Pro",
        "display": "6.1\" LTPO OLED, 120Hz, 1179x2556", "chipset": "Apple A17 Pro",
        "ram_options": ["8GB"], "storage_options": ["128GB", "256GB", "512GB", "1TB"],
        "main_camera": "48MP + 12MP + 12MP (triple, 3x tele)", "selfie_camera": "12MP",
        "battery_mah": 3274, "charging": "27W wired, 15W MagSafe, USB-C", "os": "iOS 17 (upgradable)",
        "body": "Titanium frame, IP68", "release_year": 2023,
    },
    {
        "brand": "apple", "model_key": "iphone 15 plus", "display_name": "Apple iPhone 15 Plus",
        "display": "6.7\" OLED, 60Hz, 1290x2796", "chipset": "Apple A16 Bionic",
        "ram_options": ["6GB"], "storage_options": ["128GB", "256GB", "512GB"],
        "main_camera": "48MP + 12MP (dual)", "selfie_camera": "12MP",
        "battery_mah": 4383, "charging": "20W wired, 15W MagSafe, USB-C", "os": "iOS 17 (upgradable)",
        "body": "Aluminum frame, glass back, IP68", "release_year": 2023,
    },
    {
        "brand": "apple", "model_key": "iphone 16 pro max", "display_name": "Apple iPhone 16 Pro Max",
        "display": "6.9\" LTPO OLED, 120Hz, 1320x2868", "chipset": "Apple A18 Pro",
        "ram_options": ["8GB"], "storage_options": ["256GB", "512GB", "1TB"],
        "main_camera": "48MP + 48MP + 12MP (triple, 5x tele)", "selfie_camera": "12MP",
        "battery_mah": 4685, "charging": "27W wired, 25W MagSafe, USB-C", "os": "iOS 18 (upgradable)",
        "body": "Titanium frame, IP68", "release_year": 2024,
    },
    {
        "brand": "apple", "model_key": "iphone 16 pro", "display_name": "Apple iPhone 16 Pro",
        "display": "6.3\" LTPO OLED, 120Hz, 1206x2622", "chipset": "Apple A18 Pro",
        "ram_options": ["8GB"], "storage_options": ["128GB", "256GB", "512GB", "1TB"],
        "main_camera": "48MP + 48MP + 12MP (triple, 5x tele)", "selfie_camera": "12MP",
        "battery_mah": 3582, "charging": "27W wired, 25W MagSafe, USB-C", "os": "iOS 18 (upgradable)",
        "body": "Titanium frame, IP68", "release_year": 2024,
    },
    {
        "brand": "apple", "model_key": "iphone air", "display_name": "Apple iPhone Air",
        "display": "6.5\" LTPO OLED, 120Hz, 1260x2736", "chipset": "Apple A19 Pro",
        "ram_options": ["12GB"], "storage_options": ["256GB", "512GB", "1TB"],
        "main_camera": "48MP (single)", "selfie_camera": "18MP",
        "battery_mah": 3149, "charging": "30W wired, 25W MagSafe, USB-C (optional MagSafe battery pack)",
        "os": "iOS 26", "body": "Titanium frame, 5.6mm thin, IP68", "release_year": 2025,
    },

    # ── Samsung ──────────────────────────────────────────────────────────────
    {
        "brand": "samsung", "model_key": "galaxy s25 ultra", "display_name": "Samsung Galaxy S25 Ultra",
        "display": "6.9\" LTPO AMOLED, 120Hz, 1440x3120", "chipset": "Snapdragon 8 Elite for Galaxy",
        "ram_options": ["12GB"], "storage_options": ["256GB", "512GB", "1TB"],
        "main_camera": "200MP + 50MP + 50MP + 10MP (quad, S Pen)", "selfie_camera": "12MP",
        "battery_mah": 5000, "charging": "45W wired, 15W wireless", "os": "Android 15 (One UI 7)",
        "body": "Titanium frame, glass back, IP68", "release_year": 2025,
    },
    {
        "brand": "samsung", "model_key": "galaxy s24 fe", "display_name": "Samsung Galaxy S24 FE",
        "display": "6.7\" AMOLED, 120Hz, 1080x2340", "chipset": "Exynos 2400e / Snapdragon 8 Gen 2",
        "ram_options": ["8GB"], "storage_options": ["128GB", "256GB", "512GB"],
        "main_camera": "50MP + 12MP + 8MP (triple)", "selfie_camera": "10MP",
        "battery_mah": 4700, "charging": "25W wired, 15W wireless", "os": "Android 14 (One UI 6)",
        "body": "Aluminum frame, glass back, IP68", "release_year": 2024,
    },
    {
        "brand": "samsung", "model_key": "galaxy a36", "display_name": "Samsung Galaxy A36",
        "display": "6.7\" AMOLED, 120Hz, 1080x2340", "chipset": "Snapdragon 6 Gen 3 / Exynos 1380",
        "ram_options": ["8GB"], "storage_options": ["128GB", "256GB"],
        "main_camera": "50MP + 8MP + 5MP (triple)", "selfie_camera": "13MP",
        "battery_mah": 5000, "charging": "25W wired", "os": "Android 15 (One UI 7)",
        "body": "Plastic frame, glass back, IP67", "release_year": 2025,
    },

    # ── Xiaomi / Redmi / Poco ────────────────────────────────────────────────
    {
        "brand": "redmi", "model_key": "note 14 pro", "display_name": "Xiaomi Redmi Note 14 Pro+",
        "display": "6.67\" AMOLED, 120Hz, 1220x2712", "chipset": "MediaTek Dimensity 7300-Ultra",
        "ram_options": ["8GB", "12GB"], "storage_options": ["256GB", "512GB"],
        "main_camera": "200MP + 8MP + 2MP (triple, OIS)", "selfie_camera": "20MP",
        "battery_mah": 5110, "charging": "120W wired", "os": "Android 14 (HyperOS)",
        "body": "Aluminum frame, glass back, IP68/IP69", "release_year": 2024,
    },
    {
        "brand": "redmi", "model_key": "note 15", "display_name": "Xiaomi Redmi Note 15",
        "display": "6.7\" AMOLED, 120Hz, 1220x2712", "chipset": "Snapdragon 6s Gen 3 / Dimensity 6300",
        "ram_options": ["6GB", "8GB"], "storage_options": ["128GB", "256GB"],
        "main_camera": "50MP + 8MP + 2MP (triple)", "selfie_camera": "13MP",
        "battery_mah": 6000, "charging": "33W wired", "os": "Android 15 (HyperOS 2)",
        "body": "Plastic frame, glass back, IP66/68/69", "release_year": 2025,
    },
    {
        "brand": "redmi", "model_key": "15c", "display_name": "Xiaomi Redmi 15C",
        "display": "6.9\" IPS LCD, 120Hz, 720x1600", "chipset": "MediaTek Helio G81-Ultra",
        "ram_options": ["4GB", "6GB", "8GB"], "storage_options": ["128GB", "256GB"],
        "main_camera": "50MP + AI lens (dual)", "selfie_camera": "8MP",
        "battery_mah": 6000, "charging": "18W wired", "os": "Android 15 (HyperOS 2)",
        "body": "Plastic frame and back", "release_year": 2025,
    },
    {
        "brand": "redmi", "model_key": "15", "display_name": "Xiaomi Redmi 15",
        "display": "6.9\" IPS LCD, 120Hz, 720x1600", "chipset": "Snapdragon 6s Gen 3",
        "ram_options": ["6GB", "8GB", "12GB"], "storage_options": ["128GB", "256GB"],
        "main_camera": "50MP + 2MP (dual)", "selfie_camera": "8MP",
        "battery_mah": 7000, "charging": "33W wired", "os": "Android 15 (HyperOS 2)",
        "body": "Plastic frame and back, IP64", "release_year": 2025,
    },
    {
        "brand": "xiaomi", "model_key": "14t pro", "display_name": "Xiaomi 14T Pro",
        "display": "6.67\" AMOLED, 144Hz, 1220x2712", "chipset": "MediaTek Dimensity 8300-Ultra",
        "ram_options": ["12GB"], "storage_options": ["256GB", "512GB"],
        "main_camera": "50MP + 50MP + 12MP (triple, Leica)", "selfie_camera": "32MP",
        "battery_mah": 5000, "charging": "120W wired", "os": "Android 14 (HyperOS)",
        "body": "Aluminum frame, glass back, IP68", "release_year": 2024,
    },
    {
        "brand": "xiaomi", "model_key": "14t", "display_name": "Xiaomi 14T",
        "display": "6.67\" AMOLED, 144Hz, 1220x2712", "chipset": "MediaTek Dimensity 8300-Ultra",
        "ram_options": ["8GB", "12GB"], "storage_options": ["256GB", "512GB"],
        "main_camera": "50MP + 50MP + 12MP (triple, Leica)", "selfie_camera": "32MP",
        "battery_mah": 5000, "charging": "67W wired", "os": "Android 14 (HyperOS)",
        "body": "Aluminum frame, glass back, IP68", "release_year": 2024,
    },
    {
        "brand": "poco", "model_key": "x7", "display_name": "Poco X7",
        "display": "6.67\" AMOLED, 120Hz, 1220x2712", "chipset": "MediaTek Dimensity 7300-Ultra",
        "ram_options": ["8GB", "12GB"], "storage_options": ["256GB", "512GB"],
        "main_camera": "50MP + 8MP + 2MP (triple)", "selfie_camera": "20MP",
        "battery_mah": 5110, "charging": "45W wired", "os": "Android 14 (HyperOS)",
        "body": "Aluminum frame, glass back, IP68/IP69", "release_year": 2025,
    },

    # ── Honor (continued) ────────────────────────────────────────────────────
    {
        "brand": "honor", "model_key": "x8d", "display_name": "Honor X8d",
        "display": "6.8\" AMOLED, 120Hz, 1200x2652", "chipset": "Snapdragon 6s Gen 3",
        "ram_options": ["8GB", "12GB"], "storage_options": ["256GB"],
        "main_camera": "108MP + 2MP (dual)", "selfie_camera": "16MP",
        "battery_mah": 6000, "charging": "35W wired", "os": "Android 15 (MagicOS 9)",
        "body": "Plastic frame, glass back, IP64", "release_year": 2025,
    },
    {
        "brand": "honor", "model_key": "x7d", "display_name": "Honor X7d",
        "display": "6.78\" LCD, 120Hz, 1200x2652", "chipset": "Snapdragon 6 Gen 1",
        "ram_options": ["6GB", "8GB"], "storage_options": ["256GB"],
        "main_camera": "108MP + 2MP (dual)", "selfie_camera": "8MP",
        "battery_mah": 6000, "charging": "35W wired", "os": "Android 14 (MagicOS 8)",
        "body": "Plastic frame and back", "release_year": 2025,
    },
    {
        "brand": "honor", "model_key": "x9d", "display_name": "Honor X9d",
        "display": "6.78\" AMOLED, 120Hz, curved, 1200x2652", "chipset": "Snapdragon 6 Gen 1",
        "ram_options": ["8GB", "12GB"], "storage_options": ["256GB", "512GB"],
        "main_camera": "108MP + 2MP (dual, OIS)", "selfie_camera": "16MP",
        "battery_mah": 5800, "charging": "66W wired", "os": "Android 14 (MagicOS 8)",
        "body": "Plastic frame, glass back, drop-resistant, IP65", "release_year": 2025,
    },

    # ── Huawei / Tecno / Infinix (continued) ────────────────────────────────
    {
        "brand": "huawei", "model_key": "p60 pro", "display_name": "Huawei P60 Pro",
        "display": "6.67\" LTPO OLED, 120Hz, 1220x2700", "chipset": "Snapdragon 8+ Gen 1 (4G only)",
        "ram_options": ["8GB", "12GB"], "storage_options": ["256GB", "512GB"],
        "main_camera": "48MP + 48MP + 13MP (triple, variable aperture)", "selfie_camera": "13MP",
        "battery_mah": 4815, "charging": "88W wired, 50W wireless",
        "os": "HarmonyOS / EMUI (no Google Play)", "body": "Glass/ceramic back, IP68", "release_year": 2023,
    },
    {
        "brand": "tecno", "model_key": "spark 30c", "display_name": "Tecno Spark 30C",
        "display": "6.67\" LCD, 120Hz, 720x1612", "chipset": "Unisoc T7250",
        "ram_options": ["6GB", "8GB"], "storage_options": ["128GB", "256GB"],
        "main_camera": "48MP + AI lens (dual)", "selfie_camera": "8MP",
        "battery_mah": 5000, "charging": "18W wired", "os": "Android 14 (HiOS)",
        "body": "Plastic frame and back", "release_year": 2025,
    },
    {
        "brand": "infinix", "model_key": "smart 9", "display_name": "Infinix Smart 9",
        "display": "6.6\" LCD, 90Hz, 720x1612", "chipset": "Unisoc T7250",
        "ram_options": ["3GB", "4GB"], "storage_options": ["64GB", "128GB"],
        "main_camera": "13MP + AI lens (dual)", "selfie_camera": "5MP",
        "battery_mah": 5000, "charging": "10W wired", "os": "Android 14 Go edition (XOS)",
        "body": "Plastic frame and back", "release_year": 2025,
    },
    {
        "brand": "samsung", "model_key": "galaxy s21 fe", "display_name": "Samsung Galaxy S21 FE",
        "display": "6.4\" AMOLED, 120Hz, 1080x2340", "chipset": "Exynos 2100 / Snapdragon 888",
        "ram_options": ["6GB", "8GB"], "storage_options": ["128GB", "256GB"],
        "main_camera": "12MP + 12MP + 8MP (triple)", "selfie_camera": "32MP",
        "battery_mah": 4500, "charging": "25W wired, 15W wireless", "os": "Android (One UI, upgradable)",
        "body": "Aluminum frame, plastic/glass back, IP68", "release_year": 2022,
    },
    {
        "brand": "samsung", "model_key": "galaxy a71", "display_name": "Samsung Galaxy A71",
        "display": "6.7\" AMOLED, 60Hz, 1080x2400", "chipset": "Snapdragon 730",
        "ram_options": ["6GB", "8GB"], "storage_options": ["128GB"],
        "main_camera": "64MP + 12MP + 5MP + 5MP (quad)", "selfie_camera": "32MP",
        "battery_mah": 4500, "charging": "25W wired", "os": "Android (One UI)",
        "body": "Plastic frame and back", "release_year": 2020,
    },
    {
        "brand": "samsung", "model_key": "galaxy a37", "display_name": "Samsung Galaxy A37",
        "display": "6.7\" PLS LCD, 90Hz, 1080x2400", "chipset": "Exynos 1380 / MediaTek Dimensity 6300",
        "ram_options": ["6GB", "8GB"], "storage_options": ["128GB", "256GB"],
        "main_camera": "50MP + 5MP (dual)", "selfie_camera": "13MP",
        "battery_mah": 5000, "charging": "25W wired", "os": "Android 15 (One UI 7)",
        "body": "Plastic frame and back, IP54", "release_year": 2025,
    },
    {
        "brand": "samsung", "model_key": "galaxy a17", "display_name": "Samsung Galaxy A17",
        "display": "6.7\" PLS LCD, 90Hz, 1080x2340", "chipset": "MediaTek Dimensity 6300 / Helio G99",
        "ram_options": ["4GB", "8GB"], "storage_options": ["128GB", "256GB"],
        "main_camera": "50MP + 5MP + 2MP (triple)", "selfie_camera": "13MP",
        "battery_mah": 5000, "charging": "25W wired", "os": "Android 15 (One UI 7)",
        "body": "Plastic frame and back, IP54", "release_year": 2025,
    },

    # ── Xiaomi / Redmi / Poco ────────────────────────────────────────────────
    {
        "brand": "xiaomi", "model_key": "17t pro", "display_name": "Xiaomi 17T Pro",
        "display": "6.83\" AMOLED, 144Hz, 1440x3200", "chipset": "MediaTek Dimensity 8500-Ultra",
        "ram_options": ["12GB"], "storage_options": ["256GB", "512GB"],
        "main_camera": "50MP + 50MP + 50MP (triple, periscope tele)", "selfie_camera": "32MP",
        "battery_mah": 6500, "charging": "100W wired, 50W wireless", "os": "Android 16 (HyperOS 3)",
        "body": "Aluminum frame, glass back, IP68", "release_year": 2025,
    },
    {
        "brand": "redmi", "model_key": "note 15 pro", "display_name": "Xiaomi Redmi Note 15 Pro",
        "display": "6.8\" AMOLED, 120Hz, 1220x2712", "chipset": "MediaTek Dimensity 7400-Ultra",
        "ram_options": ["8GB", "12GB"], "storage_options": ["256GB", "512GB"],
        "main_camera": "200MP + 8MP + 2MP (triple)", "selfie_camera": "32MP",
        "battery_mah": 5500, "charging": "45W wired", "os": "Android 15 (HyperOS 2)",
        "body": "Aluminum frame, glass back, IP68/IP69", "release_year": 2025,
    },

    # ── Honor ────────────────────────────────────────────────────────────────
    {
        "brand": "honor", "model_key": "600 pro", "display_name": "Honor 600 Pro",
        "display": "6.7\" AMOLED, 120Hz, 1200x2664", "chipset": "Snapdragon 8s Gen 4",
        "ram_options": ["12GB"], "storage_options": ["256GB", "512GB"],
        "main_camera": "200MP + 12MP (dual, periscope tele)", "selfie_camera": "50MP",
        "battery_mah": 5300, "charging": "80W wired, 50W wireless", "os": "Android 15 (MagicOS 9)",
        "body": "Aluminum frame, glass back, IP68/IP69", "release_year": 2025,
    },
    {
        "brand": "honor", "model_key": "600 lite", "display_name": "Honor 600 Lite",
        "display": "6.7\" AMOLED, 120Hz, 1200x2664", "chipset": "Snapdragon 6 Gen 1",
        "ram_options": ["8GB"], "storage_options": ["256GB"],
        "main_camera": "108MP + 2MP (dual)", "selfie_camera": "16MP",
        "battery_mah": 5300, "charging": "35W wired", "os": "Android 15 (MagicOS 9)",
        "body": "Plastic frame, glass back, IP64", "release_year": 2025,
    },
    {
        "brand": "honor", "model_key": "400", "display_name": "Honor 400",
        "display": "6.55\" AMOLED, 120Hz, 1200x2664", "chipset": "Snapdragon 7 Gen 3",
        "ram_options": ["8GB", "12GB"], "storage_options": ["256GB", "512GB"],
        "main_camera": "200MP + 12MP (dual)", "selfie_camera": "50MP",
        "battery_mah": 5300, "charging": "66W wired", "os": "Android 15 (MagicOS 9)",
        "body": "Aluminum frame, glass back, IP65", "release_year": 2025,
    },
    {
        "brand": "honor", "model_key": "x8b", "display_name": "Honor X8b",
        "display": "6.8\" AMOLED, 120Hz, 1200x2652", "chipset": "Snapdragon 6 Gen 1",
        "ram_options": ["8GB"], "storage_options": ["256GB"],
        "main_camera": "108MP + 2MP (dual)", "selfie_camera": "16MP",
        "battery_mah": 5800, "charging": "35W wired", "os": "Android 14 (MagicOS 8)",
        "body": "Plastic frame, glass back", "release_year": 2024,
    },
    {
        "brand": "honor", "model_key": "200 lite", "display_name": "Honor 200 Lite",
        "display": "6.7\" AMOLED, 120Hz, 1200x2652", "chipset": "Snapdragon 6 Gen 1",
        "ram_options": ["8GB"], "storage_options": ["256GB"],
        "main_camera": "108MP + 2MP (dual)", "selfie_camera": "16MP",
        "battery_mah": 5230, "charging": "35W wired", "os": "Android 14 (MagicOS 8)",
        "body": "Plastic frame, glass back", "release_year": 2024,
    },

    # ── Infinix / Tecno ──────────────────────────────────────────────────────
    {
        "brand": "infinix", "model_key": "note 50 pro", "display_name": "Infinix Note 50 Pro",
        "display": "6.78\" AMOLED, 120Hz, 1080x2436", "chipset": "MediaTek Dimensity 7300",
        "ram_options": ["8GB", "12GB"], "storage_options": ["256GB"],
        "main_camera": "108MP + 2MP (dual)", "selfie_camera": "32MP",
        "battery_mah": 5200, "charging": "45W wired", "os": "Android 14 (XOS)",
        "body": "Plastic frame, glass back, IP64", "release_year": 2025,
    },
    {
        "brand": "infinix", "model_key": "gt 30 pro", "display_name": "Infinix GT 30 Pro",
        "display": "6.78\" AMOLED, 144Hz, 1080x2436", "chipset": "MediaTek Dimensity 8400",
        "ram_options": ["12GB"], "storage_options": ["256GB", "512GB"],
        "main_camera": "50MP + 2MP (dual)", "selfie_camera": "32MP",
        "battery_mah": 5500, "charging": "45W wired", "os": "Android 15 (XOS)",
        "body": "Plastic frame, glass back", "release_year": 2025,
    },
    {
        "brand": "infinix", "model_key": "hot 10i", "display_name": "Infinix Hot 10i",
        "display": "6.78\" IPS LCD, 60Hz, 720x1640", "chipset": "MediaTek Helio G25",
        "ram_options": ["2GB", "4GB"], "storage_options": ["32GB", "64GB"],
        "main_camera": "13MP + AI lens (dual)", "selfie_camera": "8MP",
        "battery_mah": 6000, "charging": "10W wired", "os": "Android 10 (XOS)",
        "body": "Plastic frame and back", "release_year": 2021,
    },
    {
        "brand": "tecno", "model_key": "spark go 1", "display_name": "Tecno Spark Go 1",
        "display": "6.6\" IPS LCD, 90Hz, 720x1612", "chipset": "Unisoc T606",
        "ram_options": ["3GB", "4GB"], "storage_options": ["64GB"],
        "main_camera": "13MP (single)", "selfie_camera": "5MP",
        "battery_mah": 5000, "charging": "10W wired", "os": "Android 14 Go edition (HiOS)",
        "body": "Plastic frame and back", "release_year": 2024,
    },

    # ── Realme / vivo / Huawei / ZTE ─────────────────────────────────────────
    {
        "brand": "realme", "model_key": "c30s", "display_name": "Realme C30s",
        "display": "6.5\" IPS LCD, 60Hz, 720x1600", "chipset": "Unisoc T612",
        "ram_options": ["2GB", "3GB", "4GB"], "storage_options": ["32GB", "64GB"],
        "main_camera": "8MP (single)", "selfie_camera": "5MP",
        "battery_mah": 5000, "charging": "10W wired", "os": "Android 12 (realme UI Go)",
        "body": "Plastic frame and back", "release_year": 2022,
    },
    {
        "brand": "vivo", "model_key": "y53s", "display_name": "vivo Y53s",
        "display": "6.58\" IPS LCD, 60Hz, 1080x2408", "chipset": "MediaTek Helio G80/G85",
        "ram_options": ["8GB"], "storage_options": ["128GB"],
        "main_camera": "50MP + 2MP (dual)", "selfie_camera": "8MP",
        "battery_mah": 5000, "charging": "18W wired", "os": "Android 11 (Funtouch OS)",
        "body": "Plastic frame and back", "release_year": 2021,
    },
    {
        "brand": "huawei", "model_key": "nova y61", "display_name": "Huawei Nova Y61",
        "display": "6.5\" IPS LCD, 90Hz, 720x1600", "chipset": "MediaTek Helio G88",
        "ram_options": ["4GB", "8GB"], "storage_options": ["64GB", "128GB"],
        "main_camera": "50MP + AI lens (dual)", "selfie_camera": "8MP",
        "battery_mah": 5000, "charging": "22.5W wired", "os": "Android 12 (EMUI, no Google Play)",
        "body": "Plastic frame and back", "release_year": 2023,
    },
    {
        "brand": "zte", "model_key": "nubia v80 max", "display_name": "ZTE Nubia V80 Max",
        "display": "6.9\" IPS LCD, 120Hz, 1080x2460", "chipset": "Unisoc T7280",
        "ram_options": ["4GB", "8GB"], "storage_options": ["128GB", "256GB"],
        "main_camera": "50MP + 2MP (dual)", "selfie_camera": "8MP",
        "battery_mah": 6000, "charging": "18W wired", "os": "Android 14 (MyOS)",
        "body": "Plastic frame and back", "release_year": 2025,
    },
]
